version: '3.8'
services:
  lightrag:
    build: ./lightrag_api
    container_name: lightrag_gafta
    ports:
      - "9621:8000"
    volumes:
      - ./rag_data:/app/data
    env_file:
      - .env
    restart: unless-stopped
